Vagrant.configure("2") do |config|
  config.vm.box = "ale_polidori/Nextcloud"
  config.vm.box_version = "15.0.2"
  config.vm.network "private_network", ip: "192.168.11.22"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox"
end
