Vagrant.configure("2") do |config|
  config.vm.box = "ale_polidori/NethServer"
  config.vm.box_version = "7.5.1804"
  config.vm.network "private_network", ip: "192.168.11.22"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox"
end
